/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.admin;


import controllers.DoctorController;
import java.awt.BorderLayout;

import java.util.List;
import models.Doctor;
import models.Employee;
import models.Speciality;
import services.SpecialityService;

/**
 *
 * @author migue
 */
public class FormDoctor extends javax.swing.JPanel {

    private Employee admin;
    
    /**
     * Creates new form FormEmpleado
     */
    private FormDoctor() {
        initComponents();
    }
    
    public FormDoctor(Employee admin){
        this();
        this.admin = admin;
        loadSpecialitys();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        jLName = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLLastname = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLType_document = new javax.swing.JLabel();
        type_document = new javax.swing.JComboBox<>();
        jLDocument = new javax.swing.JLabel();
        document = new javax.swing.JTextField();
        jLPhone = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLSpeciality = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        btnAdd = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        specialitys = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(24, 135, 84));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        title.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Agregar Medico");
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reply_arrow_30px.png"))); // NOI18N
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLName.setForeground(new java.awt.Color(255, 255, 255));
        jLName.setText("Nombre");

        name.setBackground(new java.awt.Color(24, 135, 84));
        name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLLastname.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLLastname.setForeground(new java.awt.Color(255, 255, 255));
        jLLastname.setText("Apellidos");

        lastname.setBackground(new java.awt.Color(24, 135, 84));
        lastname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(255, 255, 255));
        lastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLType_document.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLType_document.setForeground(new java.awt.Color(255, 255, 255));
        jLType_document.setText("Tipo de documento");

        type_document.setBackground(new java.awt.Color(24, 135, 84));
        type_document.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        type_document.setForeground(new java.awt.Color(255, 255, 255));
        type_document.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tipo de documento....", "Cedula de ciudadania", " " }));
        type_document.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        type_document.setFocusable(false);
        type_document.setLightWeightPopupEnabled(false);

        jLDocument.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLDocument.setForeground(new java.awt.Color(255, 255, 255));
        jLDocument.setText("Numero de documento");

        document.setBackground(new java.awt.Color(24, 135, 84));
        document.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        document.setForeground(new java.awt.Color(255, 255, 255));
        document.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLPhone.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLPhone.setForeground(new java.awt.Color(255, 255, 255));
        jLPhone.setText("Numero de telefono");

        phone.setBackground(new java.awt.Color(24, 135, 84));
        phone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLSpeciality.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLSpeciality.setForeground(new java.awt.Color(255, 255, 255));
        jLSpeciality.setText("Especialidad");

        add.setBackground(new java.awt.Color(25, 135, 84));
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdd.setText("Guardar");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddMousePressed(evt);
            }
        });

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        alert.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        alert.setForeground(new java.awt.Color(255, 255, 255));

        specialitys.setBackground(new java.awt.Color(24, 135, 84));
        specialitys.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        specialitys.setForeground(new java.awt.Color(255, 255, 255));
        specialitys.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLType_document, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(type_document, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLSpeciality, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(specialitys, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(document)
                    .addComponent(jLDocument, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLName)
                    .addComponent(jLLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLType_document)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type_document, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLDocument)
                .addGap(6, 6, 6)
                .addComponent(document, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSpeciality)
                    .addComponent(jLPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(specialitys))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        Doctors doctors = new Doctors(this.admin);
        doctors.setLocation(0, 0);
        doctors.setSize(849, 464);
        this.removeAll();
        this.add(doctors, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMousePressed
        String name = this.name.getText();
        String lastname = this.lastname.getText();
        String type_document = (String) this.type_document.getSelectedItem();
        String document = this.document.getText();
        String phone = this.phone.getText();
        String speciality = (String) this.specialitys.getSelectedItem();
        
        Speciality special = new Speciality();
        special.setSpecialitys(speciality);
        special = new SpecialityService().getSpecialityByParams(special, this.admin);
        
        Doctor doctor = new Doctor(name, lastname, type_document, document, phone, special.getId());
        
        doctor = new DoctorController().setAddDoctor(doctor, this.admin);
        
        this.alert.setText(doctor.getAlert());
        
    }//GEN-LAST:event_btnAddMousePressed

    private void loadSpecialitys(){
        
        List<Speciality> specialitys = new SpecialityService().getSpecilitys();
        for(Speciality speciality : specialitys)
           this.specialitys.addItem(speciality.getSpecialitys());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JLabel alert;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnBack;
    private javax.swing.JTextField document;
    private javax.swing.JLabel jLDocument;
    private javax.swing.JLabel jLLastname;
    private javax.swing.JLabel jLName;
    private javax.swing.JLabel jLPhone;
    private javax.swing.JLabel jLSpeciality;
    private javax.swing.JLabel jLType_document;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JComboBox<String> specialitys;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox<String> type_document;
    // End of variables declaration//GEN-END:variables
}
