/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.BorderLayout;
import java.awt.Color;
import models.Employee;
import views.admin.Doctors;
import views.admin.Employees;
import views.admin.Profile;
import views.admin.Specialitys;


/**
 *
 * @author migue
 */
public class PanelAdmin extends javax.swing.JFrame {
    
    private Employee admin;
    /**
     * Creates new form PanelAdmin
     */
    private PanelAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public PanelAdmin(Employee admin){
        this();
        this.admin = admin;
        initData(this.admin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        nav = new javax.swing.JPanel();
        btnEmployees = new javax.swing.JPanel();
        employees = new javax.swing.JLabel();
        btnSpeciality = new javax.swing.JPanel();
        speciality = new javax.swing.JLabel();
        btnDoctors = new javax.swing.JPanel();
        doctors = new javax.swing.JLabel();
        btnClose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        btnProfile = new javax.swing.JLabel();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Central de citas");
        setBackground(new java.awt.Color(24, 135, 84));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(24, 135, 84));

        jPanel2.setBackground(new java.awt.Color(24, 135, 84));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Central De Citas");

        userName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_50px.png"))); // NOI18N
        userName.setText("Administrador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nav.setBackground(new java.awt.Color(24, 135, 84));
        nav.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        btnEmployees.setBackground(new java.awt.Color(24, 135, 84));
        btnEmployees.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        btnEmployees.setPreferredSize(new java.awt.Dimension(70, 34));

        employees.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        employees.setForeground(new java.awt.Color(255, 255, 255));
        employees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employees.setText("Empleados");
        employees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEmployeesLayout = new javax.swing.GroupLayout(btnEmployees);
        btnEmployees.setLayout(btnEmployeesLayout);
        btnEmployeesLayout.setHorizontalGroup(
            btnEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnEmployeesLayout.setVerticalGroup(
            btnEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employees, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        btnSpeciality.setBackground(new java.awt.Color(24, 135, 84));
        btnSpeciality.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        btnSpeciality.setPreferredSize(new java.awt.Dimension(169, 34));

        speciality.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        speciality.setForeground(new java.awt.Color(255, 255, 255));
        speciality.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        speciality.setText("Especialidades");
        speciality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                specialityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                specialityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                specialityMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSpecialityLayout = new javax.swing.GroupLayout(btnSpeciality);
        btnSpeciality.setLayout(btnSpecialityLayout);
        btnSpecialityLayout.setHorizontalGroup(
            btnSpecialityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(speciality, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        btnSpecialityLayout.setVerticalGroup(
            btnSpecialityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(speciality, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        btnDoctors.setBackground(new java.awt.Color(24, 135, 84));
        btnDoctors.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        btnDoctors.setPreferredSize(new java.awt.Dimension(52, 34));

        doctors.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doctors.setForeground(new java.awt.Color(255, 255, 255));
        doctors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctors.setText("Medicos");
        doctors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doctorsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doctorsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDoctorsLayout = new javax.swing.GroupLayout(btnDoctors);
        btnDoctors.setLayout(btnDoctorsLayout);
        btnDoctorsLayout.setHorizontalGroup(
            btnDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnDoctorsLayout.setVerticalGroup(
            btnDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctors, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        btnClose.setBackground(new java.awt.Color(24, 135, 84));
        btnClose.setPreferredSize(new java.awt.Dimension(86, 34));

        close.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("Cerrar sesion");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        profile.setBackground(new java.awt.Color(24, 135, 84));
        profile.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(255, 255, 255)));

        btnProfile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProfile.setText("Perfil");
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProfileMousePressed(evt);
            }
        });

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(btnSpeciality, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesMouseEntered
        // TODO add your handling code here:
        btnEmployees.setBackground(new Color(13,110,253));
    }//GEN-LAST:event_employeesMouseEntered

    private void employeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesMouseExited
        // TODO add your handling code here:
        btnEmployees.setBackground(new Color(24,135,84));
    }//GEN-LAST:event_employeesMouseExited

    private void employeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesMouseClicked
        // TODO add your handling code here:
        Employees employee = new Employees(this.admin);
        employee.setLocation(0, 0);
        employee.setSize(849, 464);
        container.removeAll();
        container.add(employee, BorderLayout.CENTER);
        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_employeesMouseClicked

    private void specialityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specialityMouseEntered
        // TODO add your handling code here:
        btnSpeciality.setBackground(new Color(13,110,253));
    }//GEN-LAST:event_specialityMouseEntered

    private void specialityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specialityMouseExited
        // TODO add your handling code here:
        btnSpeciality.setBackground(new Color(24,135,84));
    }//GEN-LAST:event_specialityMouseExited

    private void specialityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specialityMouseClicked
        // TODO add your handling code here:
        Specialitys speciality = new Specialitys(this.admin);
        speciality.setLocation(0, 0);
        speciality.setSize(849, 464);
        container.removeAll();
        container.add(speciality, BorderLayout.CENTER);
        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_specialityMouseClicked

    private void doctorsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsMouseEntered
        // TODO add your handling code here:
        btnDoctors.setBackground(new Color(13,110,253));
    }//GEN-LAST:event_doctorsMouseEntered

    private void doctorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsMouseExited
        // TODO add your handling code here:
        btnDoctors.setBackground(new Color(24,135,84));
    }//GEN-LAST:event_doctorsMouseExited

    private void doctorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsMouseClicked
        // TODO add your handling code here:
        Doctors doctor = new Doctors(this.admin);
        doctor.setLocation(0, 0);
        doctor.setSize(849, 464);
        container.removeAll();
        container.add(doctor, BorderLayout.CENTER);
        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_doctorsMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        btnClose.setBackground(new Color(13,110,253));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        btnClose.setBackground(new Color(24,135,84));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_closeMouseClicked

    private void btnProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMousePressed
        Profile profile = new Profile(this,this.admin);
        profile.setLocation(0, 0);
        profile.setSize(849, 464);
        container.removeAll();
        container.add(profile, BorderLayout.CENTER);
        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_btnProfileMousePressed

    private void btnProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseEntered
        this.profile.setBackground(new Color(13,110,253));
    }//GEN-LAST:event_btnProfileMouseEntered

    private void btnProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseExited
        this.profile.setBackground(new Color(24,135,84));
    }//GEN-LAST:event_btnProfileMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdmin().setVisible(true);
            }
        });
    }

    public void initData(Employee admin){
        userName.setText(admin.getName()+ " " + admin.getLastname() );
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnDoctors;
    private javax.swing.JPanel btnEmployees;
    private javax.swing.JLabel btnProfile;
    private javax.swing.JPanel btnSpeciality;
    private javax.swing.JLabel close;
    private javax.swing.JPanel container;
    private javax.swing.JLabel doctors;
    private javax.swing.JLabel employees;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel profile;
    private javax.swing.JLabel speciality;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
