/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.employee;

import controllers.NotificationController;
import javax.swing.table.TableColumnModel;
import models.Employee;
import models.Notification;
import views.PanelEmployee;

/**
 *
 * @author migue
 */
public class Notifications extends javax.swing.JPanel {

    private Employee employee;
    
    /**
     * Creates new form Notifications
     */
    public Notifications() {
        initComponents();
    }
    public Notifications(Employee employee){
        this();
        this.employee = employee;
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(24, 135, 84));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification_30px.png"))); // NOI18N
        jLabel1.setText("Notificaciones");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        jTable1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(24, 135, 84));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(24, 135, 84));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(24, 135, 84));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setShowGrid(true);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        String id = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1));
        Notification notification = new Notification(Integer.parseInt(id));
        
        DeleteNotification delete = new DeleteNotification(new PanelEmployee(this.employee), true, this, notification, employee);
        delete.setLocationRelativeTo(null);
        delete.setVisible(true);
    }//GEN-LAST:event_jTable1MousePressed
    
    public void loadTable(){
        jTable1.setModel(new NotificationController().getNotifications(this.employee));
        TableColumnModel model = jTable1.getColumnModel();
        model.getColumn(0).setMaxWidth(50);
        model.getColumn(0).setMinWidth(50);
        model.getColumn(0).setPreferredWidth(50);
        model.getColumn(0).setResizable(false);
        model.getColumn(1).setMaxWidth(0);
        model.getColumn(1).setMinWidth(0);
        model.getColumn(1).setPreferredWidth(0);
        model.getColumn(1).setResizable(false);
        model.getColumn(2).setMinWidth(600);
        model.getColumn(2).setMinWidth(600);
        model.getColumn(2).setPreferredWidth(600);
        model.getColumn(2).setResizable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
