/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.employee;

import controllers.CiteController;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import models.Cite;
import models.Doctor;
import models.Employee;
import models.Speciality;
import services.CiteService;
import services.DoctorService;
import services.SpecialityService;

/**
 *
 * @author migue
 */
public class UpdateCite extends javax.swing.JPanel {
    
    private Employee employee;
    private Cite cite;
    /**
     * Creates new form FormEmpleado
     */
    private UpdateCite() {
        initComponents();
       
    }
    
    public UpdateCite(Cite cite, Employee employee){
        this();
        this.employee = employee;
        this.cite = cite;
        loadForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        document = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        speciality = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JPanel();
        confirmar = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        type_document = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        eps = new javax.swing.JTextField();
        doctors = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        files = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLMotiveCanceld = new javax.swing.JLabel();
        recomendations = new javax.swing.JScrollPane();
        recommendations = new javax.swing.JTextArea();
        hour = new com.github.lgooddatepicker.components.TimePicker();
        jLHour = new javax.swing.JLabel();
        btnSolicite = new javax.swing.JPanel();
        solicite = new javax.swing.JLabel();
        btnDelete = new javax.swing.JPanel();
        delete = new javax.swing.JLabel();
        Orden = new javax.swing.JLabel();
        Authorization = new javax.swing.JLabel();
        btnOrden = new javax.swing.JPanel();
        orden = new javax.swing.JLabel();
        btnAuthorization = new javax.swing.JPanel();
        authorization = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(24, 135, 84));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setPreferredSize(new java.awt.Dimension(849, 494));

        jLabel1.setText("Actualizar Cita");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reply_arrow_30px.png"))); // NOI18N
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLabel3.setText("Nombre");
        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        name.setEditable(false);
        name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name.setBackground(new java.awt.Color(24, 135, 84));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        name.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Apellidos");
        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        lastname.setEditable(false);
        lastname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lastname.setBackground(new java.awt.Color(24, 135, 84));
        lastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lastname.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Tipo de documento");
        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Numero de documento");
        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        document.setEditable(false);
        document.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        document.setBackground(new java.awt.Color(24, 135, 84));
        document.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        document.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Numero de telefono");
        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        phone.setEditable(false);
        phone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        phone.setBackground(new java.awt.Color(24, 135, 84));
        phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        phone.setCaretColor(new java.awt.Color(255, 255, 255));
        phone.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Especialidad");
        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));

        speciality.setEditable(false);
        speciality.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        speciality.setBackground(new java.awt.Color(24, 135, 84));
        speciality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        speciality.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Medicos");
        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        btnConfirm.setBackground(new java.awt.Color(25, 135, 84));
        btnConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        confirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmar.setText("Confirmar");
        confirmar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        confirmar.setForeground(new java.awt.Color(255, 255, 255));
        confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnConfirmLayout = new javax.swing.GroupLayout(btnConfirm);
        btnConfirm.setLayout(btnConfirmLayout);
        btnConfirmLayout.setHorizontalGroup(
            btnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        btnConfirmLayout.setVerticalGroup(
            btnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        alert.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        alert.setForeground(new java.awt.Color(255, 255, 255));

        type_document.setEditable(false);
        type_document.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        type_document.setBackground(new java.awt.Color(24, 135, 84));
        type_document.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        type_document.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Eps");
        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));

        eps.setEditable(false);
        eps.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        eps.setBackground(new java.awt.Color(24, 135, 84));
        eps.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        eps.setForeground(new java.awt.Color(255, 255, 255));

        doctors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione medico..." }));
        doctors.setBackground(new java.awt.Color(25, 135, 84));
        doctors.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        doctors.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doctors.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Archivos requeridos");
        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));

        files.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Autorizacion", "Orden", "Autorizacion y Orden" }));
        files.setBackground(new java.awt.Color(24, 135, 84));
        files.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        files.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setText("Fecha");
        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));

        date.setBackground(new java.awt.Color(24, 135, 84));
        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        date.setDateFormatString("yyyy/MM/dd");
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setMinSelectableDate(new java.util.Date(-62135747926000L));

        jLMotiveCanceld.setText("Recomendaciones");
        jLMotiveCanceld.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLMotiveCanceld.setForeground(new java.awt.Color(255, 255, 255));

        recommendations.setBackground(new java.awt.Color(25, 135, 84));
        recommendations.setColumns(20);
        recommendations.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        recommendations.setForeground(new java.awt.Color(255, 255, 255));
        recommendations.setRows(5);
        recommendations.setAutoscrolls(false);
        recommendations.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        recomendations.setViewportView(recommendations);

        hour.setBackground(new java.awt.Color(24, 135, 84));
        hour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        hour.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hour.setForeground(new java.awt.Color(255, 255, 255));

        jLHour.setText("Hora de la cita");
        jLHour.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLHour.setForeground(new java.awt.Color(255, 255, 255));

        btnSolicite.setBackground(new java.awt.Color(13, 110, 253));
        btnSolicite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        solicite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        solicite.setText("Solicitar");
        solicite.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        solicite.setForeground(new java.awt.Color(255, 255, 255));
        solicite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                soliciteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnSoliciteLayout = new javax.swing.GroupLayout(btnSolicite);
        btnSolicite.setLayout(btnSoliciteLayout);
        btnSoliciteLayout.setHorizontalGroup(
            btnSoliciteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(solicite, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        btnSoliciteLayout.setVerticalGroup(
            btnSoliciteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(solicite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnDelete.setBackground(new java.awt.Color(220, 53, 69));
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete.setText("Eliminar");
        delete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnDeleteLayout = new javax.swing.GroupLayout(btnDelete);
        btnDelete.setLayout(btnDeleteLayout);
        btnDeleteLayout.setHorizontalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        btnDeleteLayout.setVerticalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Orden.setText("Orden");
        Orden.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Orden.setForeground(new java.awt.Color(255, 255, 255));

        Authorization.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Authorization.setForeground(new java.awt.Color(255, 255, 255));
        Authorization.setText("Autorizacion");

        btnOrden.setBackground(new java.awt.Color(24, 135, 84));
        btnOrden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        orden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf_30px.png"))); // NOI18N
        orden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ordenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnOrdenLayout = new javax.swing.GroupLayout(btnOrden);
        btnOrden.setLayout(btnOrdenLayout);
        btnOrdenLayout.setHorizontalGroup(
            btnOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnOrdenLayout.setVerticalGroup(
            btnOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnAuthorization.setBackground(new java.awt.Color(24, 135, 84));
        btnAuthorization.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        authorization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf_30px.png"))); // NOI18N
        authorization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                authorizationMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnAuthorizationLayout = new javax.swing.GroupLayout(btnAuthorization);
        btnAuthorization.setLayout(btnAuthorizationLayout);
        btnAuthorizationLayout.setHorizontalGroup(
            btnAuthorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(authorization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnAuthorizationLayout.setVerticalGroup(
            btnAuthorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(authorization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLMotiveCanceld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSolicite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(document, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(hour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(jLHour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(name)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(speciality)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctors, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(files, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(type_document)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnOrden, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Orden, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Authorization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAuthorization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(recomendations))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type_document, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(document, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLHour)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctors, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speciality, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Orden)
                            .addComponent(Authorization))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(files)
                    .addComponent(btnOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAuthorization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMotiveCanceld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recomendations, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSolicite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        Cites cites = new Cites(this.employee);
        cites.setLocation(0, 0);
        cites.setSize(849, 503);
        this.removeAll();
        this.add(cites, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnBackMouseClicked

    private void confirmarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMousePressed

        if(!this.doctors.getSelectedItem().equals("Seleccione medico...")){
            // obteniendo el id del doctor
            Doctor doctor = new Doctor();
            doctor.setName((String) this.doctors.getSelectedItem());
            doctor = new DoctorService().getDoctorByParams(doctor);

            // obteniendo la fecha
            SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
            String date = format.format(this.date.getDate());
            
            cite.setId_doctors(doctor.getId());
            cite.setDate(date);
            cite.setHour(this.hour.getText());
            cite.setRecommendations(this.recommendations.getText());
            cite.setId_status(2);
            
            cite = new CiteController().confirmCite(cite, employee);
            
            this.alert.setText(cite.getAlert());
           
        }else{
            alert.setText("seleccione el medico de la cita");
        }
    }//GEN-LAST:event_confirmarMousePressed

    private void soliciteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soliciteMousePressed
        this.cite.setRecommendations(recommendations.getText());
        this.cite.setRequired_files((String)files.getSelectedItem());
        
        this.cite = new CiteController().solicitedFiles(this.cite, this.employee);
        alert.setText(cite.getAlert());
    }//GEN-LAST:event_soliciteMousePressed

    private void deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMousePressed
        this.cite = new CiteService().delete(cite, employee);
        alert.setText(cite.getAlert());
        clearForm();
    }//GEN-LAST:event_deleteMousePressed

    private void ordenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordenMousePressed
        String pdf = new CiteService().getdf(this.cite, this.employee, this.cite.getOrden());
        this.openFile(pdf);
    }//GEN-LAST:event_ordenMousePressed

    private void authorizationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorizationMousePressed
        String pdf = new CiteService().getdf(this.cite, this.employee, this.cite.getAuthorization());
        this.openFile(pdf);
    }//GEN-LAST:event_authorizationMousePressed

    private void loadForm(){
        
        Date date = new Date();
        this.date.setMinSelectableDate(date);
        this.date.setDate(date);
        this.hour.setText("6:00 a. m.");
        name.setText(this.cite.getName());
        lastname.setText(this.cite.getLastname());
        type_document.setText(this.cite.getType_document());
        document.setText(this.cite.getDocument());
        phone.setText(this.cite.getPhone());
        eps.setText(this.cite.getEps());
        speciality.setText(String.valueOf(cite.getId_speciality()));
        List<Doctor> doctors = new DoctorService().getDoctorsBySpeciality(cite);
        for(Doctor doctor : doctors){
            this.doctors.addItem(doctor.getName());
        }
        
        Speciality special = new Speciality(this.cite.getId_speciality());
        special = new SpecialityService().getSpecialityById(special);
        this.speciality.setText(special.getSpecialitys());
        this.recommendations.setText(cite.getRecommendations());
        
        loadButtons();
        loadFileOrden();
        loadFileAuthorization();
    }
    
    private void loadButtons(){
        switch (this.cite.getId_status()) {
            case 1:
                btnDelete.setVisible(false);
                delete.setVisible(false);
                break;
            case 3:
                btnDelete.setVisible(true);
                delete.setVisible(true);
                btnConfirm.setVisible(false);
                confirmar.setVisible(false);
                btnSolicite.setVisible(false);
                solicite.setVisible(false);
                jLMotiveCanceld.setText("Motivo de cancelacion");
                recommendations.setText(this.cite.getMotiveCanceld());
               break;
            case 5:
                btnDelete.setVisible(false);
                delete.setVisible(false);
                break;

        }
    }
    
    private void loadFileOrden(){
        
        if(this.cite.getOrden() == null){
            Orden.setVisible(false);
            btnOrden.setVisible(false);
        }else{
            Orden.setVisible(true);
            btnOrden.setVisible(true);
        }
    }
    
    private void loadFileAuthorization(){
        if(this.cite.getAuthorization() == null){
            btnAuthorization.setVisible(false);
            Authorization.setVisible(false);
        }else{
            btnAuthorization.setVisible(true);
            Authorization.setVisible(true);
        }
    }
    
    private void clearForm(){
        name.setText("");
        lastname.setText("");
        type_document.setText("");
        document.setText("");
        phone.setText("");
        eps.setText("");
        speciality.setText("");
        recommendations.setText("");
    }
    
    private void openFile(String url){
        Desktop enlace = Desktop.getDesktop();
        try {
            enlace.browse(new URI(url));
        } catch (IOException | URISyntaxException ex) {
            System.out.println(ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Authorization;
    private javax.swing.JLabel Orden;
    private javax.swing.JLabel alert;
    private javax.swing.JLabel authorization;
    private javax.swing.JPanel btnAuthorization;
    private javax.swing.JLabel btnBack;
    private javax.swing.JPanel btnConfirm;
    private javax.swing.JPanel btnDelete;
    private javax.swing.JPanel btnOrden;
    private javax.swing.JPanel btnSolicite;
    private javax.swing.JLabel confirmar;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel delete;
    private javax.swing.JComboBox<String> doctors;
    private javax.swing.JTextField document;
    private javax.swing.JTextField eps;
    private javax.swing.JComboBox<String> files;
    private com.github.lgooddatepicker.components.TimePicker hour;
    private javax.swing.JLabel jLHour;
    private javax.swing.JLabel jLMotiveCanceld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField name;
    private javax.swing.JLabel orden;
    private javax.swing.JTextField phone;
    private javax.swing.JScrollPane recomendations;
    private javax.swing.JTextArea recommendations;
    private javax.swing.JLabel solicite;
    private javax.swing.JTextField speciality;
    private javax.swing.JTextField type_document;
    // End of variables declaration//GEN-END:variables
}
